
jobs:
  build:
    docker:
      - image: dazz111/ubuntu-sdk
    steps:
      - checkout
      - run:
          name: build recovery
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             git config --global color.ui false
             repo init --depth=1 -u git://github.com/SHRP/platform_manifest_twrp_omni.git -b v3_9.0 -g default,-device,-mips,-darwin,-notdefault 
             repo sync -j$(nproc --all)
             git clone https://github.com/SHRP-Devices/device_xiaomi_violet.git -b android-9.0 device/xiaomi/violet
             rm -rf out
             . build/envsetup.sh && lunch omni_violet-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka recoveryimage
             cd out/target/product/violet
             curl -sL https://git.io/file-transfer | sh
             ./transfer wet *.zip
             ./transfer wet recovery.img
             cd ~/tmp/recovery/out/target/product/violet/
             ZIPNAME="*.zip"
             curl -F chat_id=1033360588 -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot1744981054:AAEwTewZaL8Z6K49crBWlfRnW3Zi9Aqim6U/sendDocument
