version: 3.0
jobs:
  build:
    docker:
      - image: dazz111/ubuntu-sdk:build
    steps:
      - checkout
      - run:
          name: build recovery
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             git config --global color.ui false
             repo init --depth=1 -u git://github.com/SHRP/platform_manifest_twrp_omni.git -b v3_9.0 -g default,-device,-mips,-darwin,-notdefault 
             repo sync -j$(nproc --all)
             git clone https://github.com/SHRP-Devices/device_xiaomi_violet.git -b android-9.0 device/xiaomi/violet
             rm -rf out
             . build/envsetup.sh && lunch omni_violet-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka -j$(nproc --all) recoveryimage
             cd out/target/product/violet
             curl -sL https://git.io/file-transfer | sh
             ./transfer wet *.zip
             ./transfer wet recovery.img
             apt install wget -y
             wget https://raw.githubusercontent.com/tazz555/ntausjdohtajatis/main/rsfhsuwf.conf
             apt install python3-pip -y
             pip3 install telegram-send
             telegram-send --config rsfhsuwf.conf --file *.zip --caption "Build completed Successfully :)"
